### ISSUE TITLE
[para1] Visible NULL texture on a cup

### ISSUE THREAD

**Issue by JoelTroch** [JoelTroch/half_rats_parasomnia#12]
Reported @ ModDB by ZikShadow.

A cup in para1 has a visible NULL texture.

**Comment by JoelTroch** [comment]
[Screenshot of the cup in question](http://i1356.photobucket.com/albums/q727/ZikShadow/para10000_zpsqvajdibh.jpg).

**Comment by Thanoshld** [comment]
Yep,vl

**Comment by Thanoshld** [comment]
Yep, I found the cup too (actually a bottle). Consider it fixed.
