### ISSUE TITLE
[para7] Zombie stuck

### ISSUE THREAD

**Issue by JoelTroch** [JoelTroch/half_rats_parasomnia#13]
Reported @ ModDB by ZikShadow.

This [poor zombie](http://i1356.photobucket.com/albums/q727/ZikShadow/para70000_zpszocs0bjp.jpg) is stuck inside of a CLIP brush.

**Comment by Thanoshld** [comment]
Strange thing is, there is no clip brush there.

**Comment by JoelTroch** [comment]
Maybe moving the zombie a little would help ?

**Comment by Thanoshld** [comment]
It could. Looks like an easy fix anyway. I am on it.
