### ISSUE TITLE
[Breakables] Breakable that spawn multiple items fall outside of the world

### ISSUE THREAD

**Issue by JoelTroch** [JoelTroch/half_rats_parasomnia#14]
Reported @ ModDB by ZikShadow

"func_breakable" that spawn multiple instances of the entity are falling outside of the world.

**Comment by Thanoshld** [comment]
That's a common GoldSRC bug. Will see what I can do about it though.

**Comment by JoelTroch** [comment]
Nope, that's a bug of mine, there is little distance between the spawned items and maybe that's causing this bug

**Comment by Thanoshld** [comment]
Ours props do have to be put mid-air to work (compiles just lower them to ground level), so maybe you're right. I'll leave this fix to you then.

**Comment by JoelTroch** [comment]
Fixed in 1.1
