### ISSUE TITLE
Changing graphical options makes the game crash

### ISSUE THREAD

**Issue by Louis-MarieMatthews** [JoelTroch/half_rats_parasomnia#20]
You said you knew everything about the crashing problems but since nothing has been reported you might not be aware of this particular issue.
# Bug

1. Change any graphical option (brightness, use of HD models, resolution), it doesn't matter if you're in game or not
2. Click Ok
3. The game quits and restarts
4. The background is displayed
5. The game quits

# Expected results
 1. The game should launch normally
(I know you didn't need that part but I fancy making formal-like bug reports)
# Video
https://www.youtube.com/watch?v=PzyKteSUbZ0

**Comment by Thanoshld** [comment]
This doesn't seem like a bug, but more like a problem your PC has. Check out your monitor's resolutions and/or if you have installed the latest drivers for your graphics card, no matter how old or new.

**Comment by JoelTroch** [comment]
I don't have this issue too, please check your Half-Life integrity by right-clicking on "Half-Life" in your Steam game library -> "Properties" -> "Local files" tab -> "Verify integrity of game cache..."

**Comment by Louis-MarieMatthews** [comment]
I formated my computer. I will try what you said again once Half-Life is installed.

**Comment by Louis-MarieMatthews** [comment]
This made the problem disappear. Strange, it never occured before on any other HL mods.
