### ISSUE TITLE
The game lags a lot

### ISSUE THREAD

**Issue by Louis-MarieMatthews** [JoelTroch/half_rats_parasomnia#21]
It might not really be a bug but the game lags a lot, it looks like it is caused by wpolys (maybe made worse by a potential graphic tweak you made).
It might be a non-issue since it might be caused by the fact my computer is not very powerful.
# Bug
The game lags a lot, which makes it unplayable on my computer (certain areas have +3000 wpolys)
# Video
https://www.youtube.com/watch?v=pIzUfWqc-ZA

**Comment by Thanoshld** [comment]
Some areas do have a lower FPS rating than others, but this is worked on as we speak. Newer computers don't have a problem handling the mod though, so I believe the problem lies on your PC.

**Comment by JoelTroch** [comment]
May also be linked to issue #2

**Comment by Louis-MarieMatthews** [comment]
I formated my computer (an installation error prevented me from updating my graphic card, although I don't think it was linked to the problem I had as the version still remained somewhat current). I will try the mod again and keep you updated.

**Comment by Louis-MarieMatthews** [comment]
It looks like the problem disappeared (at least at first glance).
