### ISSUE TITLE
A wall is preventing me from shooting the bottles at the very beginning of the training map

### ISSUE THREAD

**Issue by Louis-MarieMatthews** [JoelTroch/half_rats_parasomnia#22]
At the very beginning of the first training map, I am not able to shoot the bottles because there is a wall separating me from them, no matter how long I wait. This prevents me from continuing in the training.
https://youtu.be/CSQN5g4RtEg?t=30s

**Comment by JoelTroch** [comment]
We are aware of that and this will be fixed in 1.1, don't block the spawners in the meantime

**Comment by Louis-MarieMatthews** [comment]
The spawners?
