### ISSUE TITLE
Some sentences don't play at the very beginning of the training map

### ISSUE THREAD

**Issue by Louis-MarieMatthews** [JoelTroch/half_rats_parasomnia#23]
This is a minor issue, and might be a problem with Half-Life rather than with the mod.
If, at the beginning of the first training map, I pause during a dialog (game menu, steam) then resume the game after a certain time, I won't be able to hear the dialog I was hearing when I paused the game.

https://www.youtube.com/watch?v=WWIqVOri_NY

**Comment by JoelTroch** [comment]
This is an issue within Gold Source itself, not Parasomnia
