### ISSUE TITLE
Game is crashing during transitions or picking up dynamite in paraschool

### ISSUE THREAD

**Issue by JoelTroch** [JoelTroch/half_rats_parasomnia#3]
Reported @ ModDB by John Smirnov.

The game seems to crash during level transitions (or just map changes/reloading). This also happen when picking up the dynamites being spawned by a "monstermaker" in "paraschool".

I can investigate the issues with the dynamites but I'm gonna need more details for the one with transitions/map changes because I was never able to reproduce them.

**Comment by Thanoshld** [comment]
I agree, we never had issues with map transitions. We need more info. A reminder, Parasomnia is only supported by the Steam, and not WON, version of Half-Life.

**Comment by JoelTroch** [comment]
@Thanoshld The most important crashes is about "monstermaker" with weapons (the Colt SAA and dynamites in "paraschool"), I'll have to eradicate those ones first.

**Comment by JoelTroch** [comment]
Fixed in 1.1
